apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "swoll.fullname" . }}
  labels:
    {{- include "swoll.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "swoll.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "swoll.selectorLabels" . | nindent 8 }}
        swoll: 'false'
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9095"
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "swoll.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            privileged: true
          image: "{{ .Values.image.repository }}:v{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - swoll
          - server
          - --cri=/run/containerd/containerd.sock
          - --detect-offsets
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /run/containerd/containerd.sock
              name: containerd
            - mountPath: /sys
              name: sys
      volumes:
        - name: containerd
          hostPath:
            path: /run/containerd/containerd.sock
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
