apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "swoll-controller.fullname" . }} 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "swoll-controller.serviceAccountName" . }} 
subjects:
- kind: ServiceAccount
  name: {{ template "swoll-controller.serviceAccountName" . }} 
  namespace: {{ .Release.Namespace }} 

