apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "swoll-controller.fullname" . }} 
  namespace: {{ .Release.Namespace }} 
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create

