# permissions for end users to view traces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trace-viewer-role
rules:
- apiGroups:
  - tools.swoll.criticalstack.com
  resources:
  - traces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tools.swoll.criticalstack.com
  resources:
  - traces/status
  verbs:
  - get
