# permissions for end users to edit traces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trace-editor-role
rules:
- apiGroups:
  - tools.swoll.criticalstack.com
  resources:
  - traces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tools.swoll.criticalstack.com
  resources:
  - traces/status
  verbs:
  - get
