{
 "title": "swolldash",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "query_result(count by (namespace) (swoll_node_metrics_syscall_count))"
   },
   {
    "name": "pod",
    "query": "query_result(count by (pod) (swoll_node_metrics_syscall_count{namespace=~\"$namespace\"}))"
   },
   {
    "name": "container",
    "query": "query_result(count by (container) (swoll_node_metrics_syscall_count{namespace=~\"$namespace\", pod=~\"$pod\"}))"
   },
   {
    "name": "class",
    "query": "query_result(count by (class) (swoll_node_metrics_syscall_count))"
   },
   {
    "name": "group",
    "query": "query_result(count by (group) (swoll_node_metrics_syscall_count{class=~\"$class\"}))"
   },
   { "name": "ival", "label": "ival", "query": "5m,1h,12h,24h" }
  ]
 },
 "panels": [
  { "title": "Timing / Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Class: $class Group: $group TIME SPENT IN EXECUTION",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(swoll_node_metrics_syscall_time{container=~\"$container\", group=~\"$group\", class=~\"$class\", pod=~\"$pod\", namespace=~\"$namespace\", err=\"OK\"}[$ival])/1000000) by (syscall)",
     "legendFormat": "{{syscall}}"
    }
   ]
  },
  {
   "title": "$class / $group / $class ERRNO",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(swoll_node_metrics_syscall_count{container=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\", class=~\"$class\", group=~\"$group\", err!=\"OK\"}[$ival])) by (err)",
     "legendFormat": "{{err}}"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "$container.$pod.$namespace Totals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "topk(10,sum(rate(swoll_node_metrics_syscall_count{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", class=~\"$class\", group=~\"$group\", err=\"OK\"}[$ival])) by (container,pod,namespace))",
     "legendFormat": "{{container}}.{{pod}}.{{namespace}}.count"
    },
    {
     "expr": "topk(10,sum(rate(swoll_node_metrics_syscall_count{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", class=~\"$class\", group=~\"$group\", err!=\"OK\"}[$ival])) by (container,pod,namespace))",
     "legendFormat": "{{container}}.{{pod}}.{{namespace}}.errors"
    }
   ]
  },
  {
   "title": "$container.$pod.$namespace Classification Totals",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(swoll_node_metrics_syscall_count{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", err=\"OK\"}[$ival])) by (class)",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "$container.$pod.$namespace Classification Errors",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(swoll_node_metrics_syscall_count{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", err!=\"OK\"}[$ival])) by (class)",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "$container.$pod.$namespace Classification Totals",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(swoll_node_metrics_syscall_count{container=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\", err=\"OK\"}[$ival])) by (class)",
     "legendFormat": "{{class}}.count"
    }
   ]
  },
  {
   "title": "$container.$pod.$namespace Classification Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(swoll_node_metrics_syscall_count{container=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\", err!=\"OK\"}[$ival])) by (class)",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "$container.$pod.$namespace Classification:$class Totals",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(swoll_node_metrics_syscall_count{container=~\"$container\",  pod=~\"$pod\", namespace=~\"$namespace\",  class=\"$class\", err=\"OK\"}[$ival])) by (group)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "$container.$pod.$namespace Classification:$class Errors",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(swoll_node_metrics_syscall_count{container=~\"$container\",  pod=~\"$pod\", namespace=~\"$namespace\",  class=\"$class\", err!=\"OK\"}[$ival])) by (group)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "$container.$pod.$namespace Classification: $class Totals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(swoll_node_metrics_syscall_count{container=~\"$container\",  pod=~\"$pod\", namespace=~\"$namespace\",  class=\"$class\", err=\"OK\"}[$ival])) by (group)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "$container.$pod.$namespace $class / Group Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(swoll_node_metrics_syscall_count{container=~\"$container\",  pod=~\"$pod\", namespace=~\"$namespace\", class=\"$class\", err!=\"OK\"}[$ival])) by (group)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "$class / $group / Syscall Totals",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum(rate(swoll_node_metrics_syscall_count{container=~\"$container\", class=~\"$class\", pod=~\"$pod\", namespace=~\"$namespace\",  class=\"$class\", group=\"$group\", err=\"OK\"}[$ival])) by (syscall)",
     "legendFormat": "{{syscall}}"
    }
   ]
  },
  {
   "title": "$class / $group / Syscall Errors",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sum(rate(swoll_node_metrics_syscall_count{container=~\"$container\", class=~\"$class\", pod=~\"$pod\", namespace=~\"$namespace\",  class=\"$class\", group=\"$group\", err!=\"OK\"}[$ival])) by (syscall,err)",
     "legendFormat": "{{syscall}}.{{err}}"
    }
   ]
  },
  {
   "title": "Classification:$class/$group  syscall Totals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(swoll_node_metrics_syscall_count{container=~\"$container\", class=~\"$class\", pod=~\"$pod\", namespace=~\"$namespace\",  class=\"$class\", group=\"$group\", err=\"OK\"}[$ival])) by (syscall)",
     "legendFormat": "{{syscall}}"
    }
   ]
  },
  {
   "title": "Class: $class Group: $group Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(swoll_node_metrics_syscall_count{container=~\"$container\",  pod=~\"$pod\", namespace=~\"$namespace\", class=\"$class\", group=\"$group\", err!=\"OK\"}[$ival])) by (syscall)",
     "legendFormat": "{{syscall}}"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "$class / $group / Syscall Totals",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "topk(15, sum(rate(swoll_node_metrics_syscall_count{container=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\"}[$ival])) by (syscall))",
       "legendFormat": "{{syscall}}"
      }
     ]
    },
    {
     "title": "$class / $group / Syscall Totals",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "topk(15, avg(rate(swoll_node_metrics_syscall_count{container=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\", err!=\"OK\"}[$ival])) by (syscall))",
       "legendFormat": "{{syscall}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "$namespace",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "repeat": "namespace",
     "targets": [
      {
       "expr": "sum(rate(swoll_node_metrics_syscall_count{container=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\"}[$ival])) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "repeat": "namespace",
     "targets": [
      {
       "expr": "sum(rate(swoll_node_metrics_syscall_count{container=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\", err!=\"OK\"}[$ival])) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum(rate(swoll_node_metrics_syscall_count{container=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\"}[$ival])) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "sum(rate(swoll_node_metrics_syscall_count{container=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\", err!=\"OK\"}[$ival])) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "sum(rate(swoll_node_metrics_syscall_count{container=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\"}[$ival])) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "sum(rate(swoll_node_metrics_syscall_count{container=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\", err!=\"OK\"}[$ival])) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "sum(rate(swoll_node_metrics_syscall_count{container=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\"}[$ival])) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "sum(rate(swoll_node_metrics_syscall_count{container=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\", err!=\"OK\"}[$ival])) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    }
   ]
  }
 ]
}