{{- if .Values.enabled -}}
apiVersion: {{ template "daemonset.apiVersion" . }} 
kind: DaemonSet
metadata:
    name: {{ template "swoll-server.fullname" . }}
    namespace: "{{ .Release.Namespace }}" 
spec:
  selector:
    matchLabels:
      app: {{ template "toplevel.name" . }} 
      release: {{ .Release.Name }}
  template:
    metadata:
      name: {{ template "swoll-server.fullname" . }} 
      labels:
        app: {{ template "toplevel.name" . }} 
        swoll: "false"
      annotations:
        {{- include "swoll-server.annotations" . | indent 7}}
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - effect: NoSchedule
          operator: Exists
      containers:
        - command:
          - swoll
          - server
          - --cri={{ .Values.global.criEndpoint }}
          - --listen-addr=":{{ .Values.listenPort }}"
          - --detect-offsets
          name: {{ template "swoll-server.name" . }} 
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}" 
          imagePullPolicy: "{{ .Values.global.image.pullPolicy }}" 
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: {{ .Values.global.criEndpoint }}
              name: containerd
            - mountPath: /sys
              name: sys
      volumes:
        - name: sys
          hostPath:
            path: /sys
        - name: containerd
          hostPath:
            path: {{ .Values.global.criEndpoint }} 
{{- end -}}
