apiVersion: v1
kind: Service
metadata:
  name:      swoll-probe
  namespace: swoll
spec:
  selector:
    app: swoll-probe
  type: NodePort
  ports:
    - port:       9095
      targetPort: 9095
      nodePort:   32095
