---
apiVersion: v1
kind: Namespace
metadata:
  name: swoll-test 
---
apiVersion: apps/v1
kind: Deployment  
metadata:
  name: swoll-kube-test 
  namespace: swoll-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swoll-kube-test 
  template:
    metadata:
      labels:
        app: swoll-kube-test 
    spec:
      hostPID: true
      volumes:
        - name: sys
          hostPath:
            path: /sys
        - name: containerd
          hostPath:
            path: /run/containerd/containerd.sock
      containers:
      - name: swoll-kube-test 
        image: errzey/swoll-kube-test:latest
        imagePullPolicy: Always 
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /run/containerd/containerd.sock
            name: containerd
          - mountPath: /sys
            name: sys
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: swoll-kube-test-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: swoll-kube-test-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: swoll-kube-test-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: swoll-test
